%YAML:1.0


inputImages: ./images/newCalibration
outputImages: ./images/newCalibration

capturedImagesRectified: ./images/new

capturedDisparities: ./images/disparityMaps

outputParameter: ./newCalibration
inputParameter: ./newCalibration
