%YAML:1.0

inputImages: ./images/final
outputImages: ./images/final

capturedImagesRectified: ./images/moritz_r

capturedDisparities: ./images/disparityMaps

outputParameter: ./final
inputParameter: ./final