%YAML:1.0

inputImages: ./images/smallBLFisheye
outputImages: ./images/smallBLFisheye

capturedImagesRectified: ./images/moritz_r

capturedDisparities: ./images/disparityMaps

outputParameter: ./smallBLFisheye
inputParameter: ./parameterSmallestBaseline
