%YAML:1.0

inputImages: ./images/newImages
outputImages: ./images/newImages

capturedImagesRectified: ./images/rectifiedImages

capturedDisparities: ./images/disparityMaps


outputParameter: ./parameterTest
inputParameter: ./parameter
