%YAML:1.0

inputImages: ./images/calibration_new_small_obj
outputImages: ./images/newImages

capturedImagesRectified: ./images/new

capturedDisparities: ./images/disparityMaps

outputParameter: ./calibration_new_small_obj
inputParameter: ./calibration_new_small_obj
